default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 100
  workers:
    - queues: default
      threads: 3
      processes: 1
      polling_interval: 0.2
    - queues: video_processing
      threads: 1
      processes: 1
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
